apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: kzhk0eb1l-go 
  janus-idp.io/tekton: kzhk0eb1l-go
  backstage.io/kubernetes-id: kzhk0eb1l-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kzhk0eb1l-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  